import "server-only";
import fs from "node:fs";
import path from "node:path";
import { Agent } from "undici";

/**
 * The Rust backend sits behind an nginx sidecar terminating TLS with a
 * self-signed certificate (see cert-service/nginx). Rather than disabling
 * certificate verification globally (NODE_TLS_REJECT_UNAUTHORIZED=0, which
 * would also blind the app to *real* MITM attacks), we trust exactly one
 * extra CA: the local dev CA generated by cert-service/scripts/generate-certs.sh.
 *
 * If BACKEND_CLIENT_CERT_PATH / BACKEND_CLIENT_KEY_PATH are set, the agent
 * also presents a client certificate, satisfying the mTLS nginx config
 * (nginx/nginx.mtls.conf, ssl_verify_client on).
 */

function readIfPresent(envVar: string | undefined): Buffer | undefined {
  if (!envVar) return undefined;
  const resolved = path.resolve(process.cwd(), envVar);
  if (!fs.existsSync(resolved)) {
    console.warn(`[backend-agent] configured path does not exist: ${resolved}`);
    return undefined;
  }
  return fs.readFileSync(resolved);
}

let cachedAgent: Agent | null = null;

export function getBackendAgent(): Agent {
  if (cachedAgent) return cachedAgent;

  const ca = readIfPresent(process.env.BACKEND_CA_CERT_PATH);
  const cert = readIfPresent(process.env.BACKEND_CLIENT_CERT_PATH);
  const key = readIfPresent(process.env.BACKEND_CLIENT_KEY_PATH);

  if (!ca) {
    console.warn(
      "[backend-agent] BACKEND_CA_CERT_PATH not set/found — falling back to " +
        "the system trust store, which will reject the self-signed dev cert. " +
        "Set it in .env.local (see .env.local.example)."
    );
  }

  cachedAgent = new Agent({
    connect: {
      ca,
      cert,
      key,
      // Explicit and narrow: we only relax trust for our own local CA above,
      // never for arbitrary hosts.
      rejectUnauthorized: true,
    },
  });

  return cachedAgent;
}

export const BACKEND_URL = process.env.BACKEND_URL ?? "https://localhost:8443";
